"'Product Catagories' As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":

    RectQuickActionBar1 As rectangle:
        Height: =88
        Width: =Parent.Width
        ZIndex: =1

    LblAppName1 As label:
        Align: =Align.Center
        DisabledBorderColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(227, 234, 243, 1)
        Height: =88
        Size: =27
        Text: ="[Title]"
        Width: =Parent.Width
        ZIndex: =2

    Canvas1 As fluidGrid.fluidGridWithBlankCard:
        BorderThickness: =0
        Height: =Parent.Height - Self.Y
        Width: =Parent.Width
        Y: =RectQuickActionBar1.Y + RectQuickActionBar1.Height
        ZIndex: =3

        DataCard1 As dataCard:
            BorderColor: =RGBA(0, 0, 0, 1)
            BorderStyle: =BorderStyle.Solid
            BorderThickness: =0
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(0, 0, 0, 0)
            Height: =Parent.Height - 100
            Width: =Parent.Width
            X: =0
            Y: =0
            ZIndex: =1

            Label4 As label:
                Height: =62
                Size: =21
                Text: ="Product Categories"
                Width: =315
                X: =18
                Y: =90
                ZIndex: =1

            TextInput1 As text:
                Default: ="Text input"
                Height: =44
                Size: =21
                Width: =252
                X: =352
                Y: =30
                ZIndex: =2

            "'Ayam Perap pc' As groupContainer.manualLayoutContainer":
                Height: =187
                Width: =542
                X: =48
                Y: =168
                ZIndex: =3

                Label6 As label:
                    Height: =42
                    Size: =21
                    Text: ="Ayam"
                    Width: =182
                    X: =220
                    Y: =80
                    ZIndex: =1

                Image6 As image:
                    Height: =187
                    Image: =ayam
                    Width: =157
                    ZIndex: =2

            Meatball As groupContainer.manualLayoutContainer:
                Height: =187
                Width: =542
                X: =48
                Y: =408
                ZIndex: =4

                Label6_1 As label:
                    Height: =42
                    Size: =21
                    Text: ="Lembu"
                    Width: =182
                    X: =205
                    Y: =72
                    ZIndex: =1

                Image7 As image:
                    Height: =187
                    Image: ='download (2) (1)'
                    Width: =160
                    ZIndex: =2

            "'Kambing Perap pc' As groupContainer.manualLayoutContainer":
                Height: =175
                Width: =542
                X: =48
                Y: =656
                ZIndex: =5

                Label6_2 As label:
                    Height: =42
                    Size: =21
                    Text: ="Meatball"
                    Width: =182
                    X: =190
                    Y: =66
                    ZIndex: =1

                Image8 As image:
                    Height: =175
                    Image: ='download (1)'
                    Width: =162
                    ZIndex: =2

            "'Lembu Perap pc' As groupContainer.manualLayoutContainer":
                Height: =175
                Width: =542
                X: =48
                Y: =894
                ZIndex: =6

                Label6_3 As label:
                    Height: =42
                    Size: =21
                    Text: ="Kambing"
                    Width: =182
                    X: =180
                    Y: =56
                    ZIndex: =1

            Combo As groupContainer.manualLayoutContainer:
                Height: =202
                Width: =542
                X: =48
                Y: =1133
                ZIndex: =7

                Label6_4 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =40
                    Y: =40
                    ZIndex: =1

