"'Product Catagories' As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":

    RectQuickActionBar1 As rectangle:
        Height: =88
        Width: =Parent.Width
        ZIndex: =1

    LblAppName1 As label:
        Align: =Align.Center
        DisabledBorderColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(227, 234, 243, 1)
        Height: =88
        Size: =27
        Text: ="[Title]"
        Width: =Parent.Width
        ZIndex: =2

    Canvas1 As fluidGrid.fluidGridWithBlankCard:
        BorderThickness: =0
        Height: =Parent.Height - Self.Y
        Width: =Parent.Width
        Y: =RectQuickActionBar1.Y + RectQuickActionBar1.Height
        ZIndex: =3

        DataCard1 As dataCard:
            BorderColor: =RGBA(0, 0, 0, 1)
            BorderStyle: =BorderStyle.Solid
            BorderThickness: =0
            DisplayMode: =DisplayMode.Disabled
            Fill: =RGBA(0, 0, 0, 0)
            Height: =Parent.Height - 100
            Width: =Parent.Width
            X: =0
            Y: =0
            ZIndex: =1

            Label4 As label:
                Height: =62
                Size: =21
                Text: ="Product Categories"
                Width: =315
                X: =18
                Y: =90
                ZIndex: =1

            TextInput1 As text:
                Default: ="Text input"
                Height: =44
                Size: =21
                Width: =252
                X: =352
                Y: =30
                ZIndex: =2

            "'Ayam Perap' As groupContainer.manualLayoutContainer":
                Height: =202
                Width: =542
                X: =48
                Y: =168
                ZIndex: =3

                Label6 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =218
                    Y: =58
                    ZIndex: =1

            Meatball As groupContainer.manualLayoutContainer:
                Height: =202
                Width: =542
                X: =48
                Y: =406
                ZIndex: =4

                Label6_1 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =40
                    Y: =40
                    ZIndex: =1

            "'Kambing Perap' As groupContainer.manualLayoutContainer":
                Height: =202
                Width: =542
                X: =49
                Y: =648
                ZIndex: =5

                Label6_2 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =40
                    Y: =40
                    ZIndex: =1

            "'Lembu Perap' As groupContainer.manualLayoutContainer":
                Height: =202
                Width: =542
                X: =48
                Y: =890
                ZIndex: =6

                Label6_3 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =40
                    Y: =40
                    ZIndex: =1

            Combo As groupContainer.manualLayoutContainer:
                Height: =202
                Width: =542
                X: =48
                Y: =1133
                ZIndex: =7

                Label6_4 As label:
                    Height: =42
                    Size: =21
                    Text: ="Text"
                    Width: =182
                    X: =40
                    Y: =40
                    ZIndex: =1

